### ISSUE TITLE
Maschinenzahl berechnen

### ISSUE THREAD

**Issue by Newoss** [it22sum/useful-numerical-math-scripts#37]
Maschinenzahl berechnen mit Dezimalzahl, unterschiedlichen Mantisse und Exponent

**Comment by Newoss** [comment]
@yhlbr & @fiechdus könnt ihr den Code überprüfen ob der so passt oder ob ihr Verbesserungen habt?
Berechnung von Gleitkommazahlen (Dezimal) in binär ist vorhanden und könnte man für den Converter von Dez zu binär verwenden.

**Comment by yhlbr** [comment]
@Newoss kannst du einen MR machen? Sonst kann ich es nicht reviewen wenn ich den MR selbst eröffne.
